apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsradar.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsradar.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.secrets.githubToken | quote }}
  github-repo: {{ .Values.secrets.githubRepo | quote }}
  api-key: {{ .Values.secrets.apiKey | quote }}
