apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-limits-app
  namespace: ops-radar-demo
  labels:
    app: missing-limits-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-limits-app
  template:
    metadata:
      labels:
        app: missing-limits-app
    spec:
      containers:
        - name: web
          image: nginx:1.25
          ports:
            - containerPort: 80
          # ISSUE: no resource requests
          # ISSUE: no resource limits
          # ISSUE: no livenessProbe
          # ISSUE: no readinessProbe
