package pr

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/opsradar/k8s-ops-radar/api/internal/store"
)

// Generator creates GitHub PRs with fix patches.
type Generator struct {
	token string
	repo  string // "owner/repo"
	client *http.Client
}

// NewGenerator creates a PR Generator.
func NewGenerator(token, repo string) *Generator {
	return &Generator{
		token:  token,
		repo:   repo,
		client: &http.Client{Timeout: 30 * time.Second},
	}
}

// GeneratePR creates a branch with the finding's diff patch and opens a PR.
// Returns the HTML URL of the created PR.
func (g *Generator) GeneratePR(ctx context.Context, f store.Finding) (string, error) {
	if g.token == "" || g.repo == "" {
		return "", fmt.Errorf("GITHUB_TOKEN and GITHUB_REPO must be set")
	}

	// 1. Get default branch SHA
	defaultBranch, sha, err := g.getDefaultBranchSHA(ctx)
	if err != nil {
		return "", fmt.Errorf("get default branch: %w", err)
	}

	// 2. Create branch
	branchName := fmt.Sprintf("opsradar/fix-%s", f.ID[:8])
	if err := g.createBranch(ctx, branchName, sha); err != nil {
		return "", fmt.Errorf("create branch: %w", err)
	}

	// 3. Commit the patch as a file
	commitMsg := fmt.Sprintf("fix: %s", f.Title)
	if err := g.commitPatch(ctx, branchName, f, commitMsg); err != nil {
		return "", fmt.Errorf("commit patch: %w", err)
	}

	// 4. Open PR
	prURL, err := g.openPR(ctx, branchName, defaultBranch, f)
	if err != nil {
		return "", fmt.Errorf("open pr: %w", err)
	}
	return prURL, nil
}

func (g *Generator) getDefaultBranchSHA(ctx context.Context) (branch, sha string, err error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s", g.repo)
	body, err := g.githubGET(ctx, url)
	if err != nil {
		return "", "", err
	}
	var repo struct {
		DefaultBranch string `json:"default_branch"`
	}
	if err := json.Unmarshal(body, &repo); err != nil {
		return "", "", err
	}

	refURL := fmt.Sprintf("https://api.github.com/repos/%s/git/refs/heads/%s", g.repo, repo.DefaultBranch)
	refBody, err := g.githubGET(ctx, refURL)
	if err != nil {
		return "", "", err
	}
	var ref struct {
		Object struct {
			SHA string `json:"sha"`
		} `json:"object"`
	}
	if err := json.Unmarshal(refBody, &ref); err != nil {
		return "", "", err
	}
	return repo.DefaultBranch, ref.Object.SHA, nil
}

func (g *Generator) createBranch(ctx context.Context, name, sha string) error {
	url := fmt.Sprintf("https://api.github.com/repos/%s/git/refs", g.repo)
	payload := map[string]string{
		"ref": "refs/heads/" + name,
		"sha": sha,
	}
	_, err := g.githubPOST(ctx, url, payload)
	return err
}

func (g *Generator) commitPatch(ctx context.Context, branch string, f store.Finding, message string) error {
	// Encode the patch as a new file
	fileName := fmt.Sprintf("patches/opsradar-fix-%s.patch", f.ID[:8])
	contentB64 := b64Encode([]byte(f.DiffPatch))

	url := fmt.Sprintf("https://api.github.com/repos/%s/contents/%s", g.repo, fileName)
	payload := map[string]string{
		"message": message,
		"content": contentB64,
		"branch":  branch,
	}
	_, err := g.githubPOST(ctx, url, payload)
	return err
}

func (g *Generator) openPR(ctx context.Context, head, base string, f store.Finding) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/pulls", g.repo)
	payload := map[string]string{
		"title": fmt.Sprintf("OpsRadar fix: %s", f.Title),
		"head":  head,
		"base":  base,
		"body":  fmt.Sprintf("**Finding:** %s\n\n**Detail:** %s\n\n**Suggestion:** %s\n\n---\n*Generated by OpsRadar*", f.Title, f.Detail, f.Suggestion),
	}
	body, err := g.githubPOST(ctx, url, payload)
	if err != nil {
		return "", err
	}
	var pr struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.Unmarshal(body, &pr); err != nil {
		return "", err
	}
	return pr.HTMLURL, nil
}

func (g *Generator) githubGET(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	g.setHeaders(req)
	resp, err := g.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return readBody(resp)
}

func (g *Generator) githubPOST(ctx context.Context, url string, payload any) ([]byte, error) {
	data, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, url, strings.NewReader(string(data)))
	if err != nil {
		return nil, err
	}
	// Use POST for refs/pulls, PUT for contents
	if strings.Contains(url, "/pulls") || strings.Contains(url, "/refs") {
		req.Method = http.MethodPost
	}
	g.setHeaders(req)
	resp, err := g.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return readBody(resp)
}

func (g *Generator) setHeaders(req *http.Request) {
	req.Header.Set("Authorization", "Bearer "+g.token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("Content-Type", "application/json")
}

func readBody(resp *http.Response) ([]byte, error) {
	var buf strings.Builder
	buf.Grow(4096)
	b := make([]byte, 4096)
	for {
		n, err := resp.Body.Read(b)
		if n > 0 {
			buf.Write(b[:n])
		}
		if err != nil {
			break
		}
	}
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("github API %d: %s", resp.StatusCode, buf.String())
	}
	return []byte(buf.String()), nil
}

// b64Encode base64-encodes bytes (std encoding, as required by GitHub API).
func b64Encode(data []byte) string {
	const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	var sb strings.Builder
	for i := 0; i < len(data); i += 3 {
		var b [3]byte
		n := copy(b[:], data[i:])
		sb.WriteByte(chars[b[0]>>2])
		sb.WriteByte(chars[(b[0]&3)<<4|b[1]>>4])
		if n > 1 {
			sb.WriteByte(chars[(b[1]&15)<<2|b[2]>>6])
		} else {
			sb.WriteByte('=')
		}
		if n > 2 {
			sb.WriteByte(chars[b[2]&63])
		} else {
			sb.WriteByte('=')
		}
	}
	return sb.String()
}
